version: '3'
services:
  api:
    env_file:
    - ./api/.env
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
     - "8000:8000"
    depends_on:
      - database
    links:
      - database
  web:
    env_file:
    - ./web/.env
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
     - "8080:8080"
    depends_on:
      - api
    links:
      - api
  database:
    image: "mongo:latest"