version: '3'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
     - "8000:8000"
    volumes:
     - ./api:/api
    enviroment:
      - API_PORT: 8000
    # depends_on:
    #   - database
  # web:
  #   build:
  #   ports:
  #   - "8001:8001"
  # database:
  #   image: "mongo:latest"
