version: '3'
services:
  api:
    env_file:
    - ./api/.env
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
     - "8000:8000"
    volumes:
     - ./api:/api
    depends_on:
      - database
    links:
      - database
  web:
    env_file:
    - ./web/.env
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    volumes:
     - ./web:/web
    ports:
     - "7777:7777"
    # depends_on:
    #   - api
  database:
    image: "mongo:latest"
    ports:
      - "27018:27017"
