version: '3'
services:
  api:
    build: ./api
    ports:
     - "8000:8000"
    depends_on:
      - database
    enviroment:
      - API_PORT: 8000
  # web:
  #   build:
  #   ports:
  #   - "8001:8001"
  database:
    image: "mongo:latest"
