build:
	docker-compose build

start:
	docker-compose up
	
# Dev enviroment
dev-build:
	docker-compose --file "docker-compose.dev.yml" build 

dev-start:
	docker-compose --file "docker-compose.dev.yml" up 

# Cleans all stuff generated by Docker
clean:
	docker-compose down